name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TF_VERSION: 1.1.7
  AZURE_SUBSCRIPTION: ${{ secrets.AZURE_SUBSCRIPTION }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Terraform Init
      run: terraform init -input=false
      working-directory: ./infrastructure
    
    - name: Terraform Validate
      run: terraform validate
      working-directory: ./infrastructure

  deploy:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Infrastructure
      run: |
        cd infrastructure
        terraform init
        terraform apply -auto-approve \
          -var="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
          -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
    
    - name: Build and Push Frontend
      run: |
        cd src/frontend
        docker build -t mediaassistant.azurecr.io/frontend:${{ github.sha }} .
        echo ${{ secrets.ACR_PASSWORD }} | docker login mediaassistant.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
        docker push mediaassistant.azurecr.io/frontend:${{ github.sha }}
    
    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group media-assistant-rg --name media-assistant-aks
        kubectl set image deployment/frontend frontend=mediaassistant.azurecr.io/frontend:${{ github.sha }}
